# Generated by Django 5.1.5 on 2025-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_surgicalproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitaminProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vitamins/')),
            ],
        ),
        migrations.AlterField(
            model_name='surgicalproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='surgical_products/'),
        ),
    ]
