# Generated by Django 5.1.5 on 2025-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_vitaminproduct_alter_surgicalproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dental_products/')),
            ],
        ),
    ]
