# Generated by Django 5.1.5 on 2025-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_doctor_appointment_time_alter_doctor_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Dash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=100)),
                ('medical_college', models.CharField(max_length=200)),
                ('appointment_time', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('visit_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='appointment_time',
            field=models.CharField(blank=True, default='09:00 AM - 05:00 PM', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, default='Not Set'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='medical_college',
            field=models.CharField(blank=True, default='Not Set', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='payment_method',
            field=models.CharField(default='bKash', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='visit_fee',
            field=models.IntegerField(default=1000),
        ),
    ]
