# Generated by Django 5.1.5 on 2025-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_doctor_dash_alter_doctor_appointment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_dash',
            name='appointment_time',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor_dash',
            name='bio',
            field=models.TextField(blank=True, default='Not Set'),
        ),
        migrations.AlterField(
            model_name='doctor_dash',
            name='medical_college',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor_dash',
            name='payment_method',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor_dash',
            name='visit_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
