# Generated by Django 5.1.5 on 2025-10-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
