# Generated by Django 5.1.5 on 2025-10-13 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_alter_prescription_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='Doctor_Dash',
            name='user',
            field=models.OneToOneField(
                to=settings.AUTH_USER_MODEL,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE
            ),
            preserve_default=False,
        ),
    ]
