# Generated by Django 5.1.5 on 2025-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_alter_doctor_dash_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_dash',
            name='receive_appointment_reminder',
            field=models.BooleanField(default=True, help_text='Receive reminders for scheduled appointments.'),
        ),
        migrations.AddField(
            model_name='doctor_dash',
            name='receive_message_alerts',
            field=models.BooleanField(default=False, help_text='Receive alerts for direct patient messages.'),
        ),
        migrations.AddField(
            model_name='doctor_dash',
            name='receive_new_request_notif',
            field=models.BooleanField(default=True, help_text='Receive alerts for new prescription requests.'),
        ),
        migrations.AddField(
            model_name='doctor_dash',
            name='receive_performance_report',
            field=models.BooleanField(default=True, help_text='Receive weekly performance reports.'),
        ),
    ]
