# Generated by Django 5.1.5 on 2025-10-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_doctor_dash_receive_appointment_reminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_dash',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
