# Generated by Django 5.1.5 on 2025-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('blood_type', models.CharField(max_length=3)),
                ('available_for_donations', models.BooleanField(default=True)),
            ],
        ),
    ]
